#!/bin/bash

# Take quick notes from the command line
notes() {
  if [ ! -z "$1" ]; then
    # Using the "$@" here will take all parameters passed into
    # this function so we can place everything into our file.
    echo "$@" >> "$notes/memo-cli-oneliners.txt"
  else
    # If no arguments were passed we will take stdin and place
    # it into our notes instead.
    cat - >> "$notes/memo-cli-oneliners.txt"
  fi
}
